---
- name: Add user
  hosts: 192.168.200.71
  tasks:
  - name: Install my_collection from Ansible Galaxy
    command: ansible-galaxy collection install ansible.network.routeros
    become: true

  - name: Add test user 
    routeros_command:
     commands: /user add name=test group=test password=test

