---
- name: using a REST API
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: "Let's Automate"
    
    - name: Fetch all interfaces of the mikrotik router
      uri:
        url: http://192.168.200.71/rest/interface
        method: GET
        url_username: admin
        force_basic_auth: yes
        validate_certs: false
